(function(win){var elements=[];function Food(x,y,width,height,color){this.x=x||0;this.y=y||0;this.width=width||20;this.height=height||20;this.color=color||"green";}
    Food.prototype.init=function(map){remove();var div=document.createElement("div");div.style.width=this.width+"px";div.style.height=this.height+"px";div.style.backgroundColor=this.color;div.style.position="absolute";this.x=parseInt(map.offsetWidth/this.width*Math.random());this.y=parseInt(map.offsetHeight/this.height*Math.random());div.style.left=this.x*this.width+"px";div.style.top=this.y*this.height+"px";map.appendChild(div);elements.push(div);};function remove(){for(var i=0;i<elements.length;i++){var e=elements[i];e.parentNode.removeChild(e);elements.splice(i,1);}}
    win.Food=Food;})(window);(function(win){var elements=[];function Snake(width,height,direction){this.body=[{x:3,y:2,color:"red"},{x:2,y:2,color:"green"},{x:1,y:2,color:"green"}];this.width=width||0;this.height=height||0;this.direction=direction||"right";}
    Snake.prototype.init=function(map){remove();for(var i=0;i<this.body.length;i++){var bodyi=this.body[i];var div=document.createElement("div");div.style.width=this.width+"px";div.style.height=this.height+"px";div.style.backgroundColor=bodyi.color;div.style.position="absolute";div.style.left=bodyi.x*this.width+"px";div.style.top=bodyi.y*this.height+"px";map.appendChild(div);elements.push(div);}};function remove(){for(var i=elements.length-1;i>=0;i--){var e=elements[i];e.parentNode.removeChild(e);elements.splice(i,1);}}
    Snake.prototype.move=function(map,food){var len=this.body.length-1;for(var i=len;i>0;i--){this.body[i].x=this.body[i-1].x;this.body[i].y=this.body[i-1].y;}
        switch(this.direction){case"right":this.body[0].x+=1;break;case"left":this.body[0].x-=1;break;case"top":this.body[0].y-=1;break;case"bottom":this.body[0].y+=1;break;default:break;}
        if(this.body[0].x==food.x&&this.body[0].y==food.y){food.init(map);var last=this.body[2];this.body.push({x:last.x,y:last.y,color:last.color});}
        this.init(map);};win.Snake=Snake;})(window);(function(win){function Game(){this.map=my$("map");this.food=new Food(0,0,20,20,"green");this.snake=new Snake(20,20,"right");}
    Game.prototype.startGame=function(){this.bindkey();this.food.init(this.map);this.snake.init(this.map);var timer=setInterval(function(){this.snake.move(this.map,this.food);var aadead=isdead.bind(this);aadead(timer);}.bind(this),200);};function isdead(timer){console.log(this);var headX=this.snake.body[0].x;var headY=this.snake.body[0].y;if(headX<0||headX>=this.map.offsetWidth/this.snake.width){clearInterval(timer);alert("游戏结束");}
        if(headY<0||headY>=this.map.offsetHeight/this.snake.height){clearInterval(timer);alert("游戏结束");}
        for(var i=1;i<this.snake.body.length;i++){var bodyi=this.snake.body[i];if(bodyi.x==headX&&bodyi.y==headY){clearInterval(timer);alert("游戏结束");break;}}}
    Game.prototype.bindkey=function(){document.onkeydown=function(e){var oev=e||window.event;switch(oev.keyCode){case 37:if(this.snake.direction=="right"||this.snake.direction=="left"){break;}
        this.snake.direction="left";break;case 38:if(this.snake.direction=="top"||this.snake.direction=="bottom"){break;}
        this.snake.direction="top";break;case 39:if(this.snake.direction=="right"||this.snake.direction=="left"){break;}
        this.snake.direction="right";break;case 40:if(this.snake.direction=="top"||this.snake.direction=="bottom"){break;}
        this.snake.direction="bottom";break;default:break;}}.bind(this);};win.Game=Game;})(window);